Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -61,16 +61,16 @@ jobs:
           wget "https://chromedriver.storage.googleapis.com/$version_3_detail/chromedriver_win32.zip" -O "chromedriver$version_3_detail.zip"
           
           {
-          version_lastest=$(($version_big+1))
-          echo $version_lastest
-          version_lastest_detail=$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$version_lastest)
-          echo $version_lastest_detail
-          echo "artifactPathLastes=chromedriver$version_lastest_detail.zip" >> $GITHUB_ENV
-          echo "artifactNameLastes=Chrome Driver Win32 v$version_lastest_detail" >> $GITHUB_ENV
-          wget "https://chromedriver.storage.googleapis.com/$version_lastest_detail/chromedriver_win32.zip" -O "chromedriver$version_lastest_detail.zip"
-         } || {
-         echo "$(($version_big+1)) fail"
-         }
+            version_lastest=$(($version_big+1))
+            echo $version_lastest
+            version_lastest_detail=$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$version_lastest)
+            echo $version_lastest_detail
+            echo "artifactPathLastes=chromedriver$version_lastest_detail.zip" >> $GITHUB_ENV
+            echo "artifactNameLastes=Chrome Driver Win32 v$version_lastest_detail" >> $GITHUB_ENV
+            wget "https://chromedriver.storage.googleapis.com/$version_lastest_detail/chromedriver_win32.zip" -O "chromedriver$version_lastest_detail.zip"
+          } || {
+            echo "$(($version_big+1)) fail"
+          }
           curl https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/LATEST_STABLE --output LATEST_CANARY
           version=$(echo `cat LATEST_CANARY` | grep -Eo '[0-9]+.[0-9]+.[0-9]+.[0-9]+')
           version_big=$(echo $version | grep -o -E '^[0-9]+')
